taosdata/grafanaplugin

dist/plugin.json, package-lock.json, package.json, yarn.lock
=> fix repo behind tdengine/.../grafana

README.md, dist/plugin.json, src/plugin.json
=> fix few issues complained by grafana plugin repo.

dashboard/tdengine-grafana-7.x.json
=> [TD-10477]<fix>: a much better dashboard for 7.x grafana

dashboards/TDinsight.json, docker-compose.yml
See https://jira.taosdata.com:18080/browse/TD-11147 .
=> [TD-11147]<fix>: fill(null) caused taosadapter/httpd coredump

dashboards/TDinsight-CN.md, dashboards/TDinsight.md
See
- https://www.taosdata.com/en/documentation/tools/insight
- https://www.taosdata.com/cn/documentation/tools/insight
=> [TD-11900]<docs>: remove toc and fix images display in website

src/config_ctrl.js, src/datasource.js, src/partials/config.html
Ref: [TD-15249](https://jira.taosdata.com:18080/browse/TD-15249)
=> feat: add config option for cloud service token

.github/workflows/ci.yaml, .github/workflows/release.yaml, package.json
Ref: [TD-15577](https://jira.taosdata.com:18080/browse/TD-15577)
=> ci: sign plugin before release

.gitignore, Gruntfile.js, docker-compose.yml, grafana/provisioning/datasources/tdengine.yml, grafana/provisioning/notifiers/tdengine.yaml, pkg/config.go, pkg/sms.go, pkg/smsworker.go, pkg/tdengine.go, src/config_ctrl.js, src/datasource.js, src/partials/config.html, src/plugin.json
Requested by Grafana review team(Brian).
Ref: [TD-15925](https://jira.taosdata.com:18080/browse/TD-15925).
=> feat: store user, password, token in secureJsonData

go.mod, go.sum, pkg/tdengine.go, pkg/tdengine_test.go
Ref: [TD-16003](https://jira.taosdata.com:18080/browse/TD-16003)
=> fix: remove sentitive logging, fix ts layout format parsing method

README.md, grafana/provisioning/datasources/tdengine.yml, pkg/config.go, pkg/tdengine.go
Remove user/password requirements in provisioning config.
=> fix: remove user/password in backend plugin config

README.md, install.sh, src/plugin.json
Ref: [TD-16366](https://jira.taosdata.com:18080/browse/TD-16366)
=> feat: add install.sh as one-line installer

dashboards/TDinsight.sh
Ref: [TD-16392](https://jira.taosdata.com:18080/browse/TD-16392)
=> fix: fix --plugin-version bug and support cloud token like install.sh

install.sh, scripts/release.sh
Ref: [TD-16437](https://jira.taosdata.com:18080/browse/TD-16437)
=> enh: do not cache zip file when there's no python in system

.github/workflows/release-pr-merged.yaml, .github/workflows/release-pr.yaml, scripts/release.sh
Just by title the pr with:
```
chore(release): v<version>
```
=> enh: anyone can request a release by pr

.github/workflows/ci.yaml, .github/workflows/release-pr-merged.yaml, .github/workflows/release-pr.yaml
Request to create a new release by a pr titled as `release: v<version>`.
=> release: v3.2.6

.github/workflows/ci.yaml, README.md
Ref: [TD-16448](https://jira.taosdata.com:18080/browse/TD-16448)
=> docs: update README for data source name settings

dashboards/TDinsight.sh, install.sh
Ref: [TS-1656](https://jira.taosdata.com:18080/browse/TS-1656)
=> fix: fix offline plugin not found error

.github/workflows/release.yaml, dashboards/TDinsight.sh
=> chore: update download url to fix downloading hangout

dashboards/TDinsight.sh
Closes [TD-18418](https://jira.taosdata.com:18080/browse/TD-18418)
=> fix: fix TDinsight.sh --offline error

.github/workflows/ci.yaml, src/dashboards/TDinsightV3.json
Jira: https://jira.taosdata.com:18080/browse/TD-
=> feat: add adapter metrics: connetion pool and status

CHANGELOG.md, INSTALLATION.md, package.json, src/dashboards/TDinsightV3.md, src/plugin.json
Jira: https://jira.taosdata.com:18080/browse/TS-6541
=> docs: update version to 3.7.2

.github/workflows/release.yaml
Jira: https://jira.taosdata.com:18080/browse/TD-
=> fix: Update release.yaml to use new cache version

.github/workflows/release.yaml
Jira: https://jira.taosdata.com:18080/browse/TD-
=> ci: copy release file to official site

.github/workflows/release.yaml
Jira: https://jira.taosdata.com:18080/browse/TD-
=> reverse release.yaml
